### ISSUE TITLE
Memcached keys not showing

### ISSUE THREAD

**Issue by kcsso** [RobiNN1/phpCacheAdmin#15]
**phpCacheAdmin Version**: v1.1.0
**PHP Version**: PHP 7.4.30 (cli)

Memcached keys & count key value is not showing like this img
https://imgur.com/0NZrCJO

But changing the code, count all key value is showing
https://imgur.com/lHmkAWE
```
    private function serverInfo(array $servers): array {
        try {
            $memcached = $this->connect($servers[Http::get('panel', 'int')]);
            $server_info = $memcached->getServerStats();

            return [
                'Version'          => $server_info['version'],
                'Open connections' => $server_info['curr_connections'],
                'Uptime'           => Format::seconds((int) $server_info['uptime']),
                'Cache limit'      => Format::bytes((int) $server_info['limit_maxbytes']),
                'Used'             => Format::bytes((int) $server_info['bytes']),
                //'Keys'             => Format::number(count($memcached->getKeys())),
                'Keys'             => Format::number(count($memcached->getallKeys())),
            ];
        } catch (DashboardException $e) {
            return [
                'error' => $e->getMessage(),
            ];
        }
    }
```

how to solve this problem..? I want to manage my Memcached key list by this dashboard. :'(

**Comment by RobiNN1** [comment]
Your Memcached server is a bit old. My tool use `lru_crawler` which requires at least Memcached 1.5.

Originally phpCacheAdmin used `cachedump` to retrieve all keys but this has many problems. E.g. it randomly displayed few keys and sometimes it didn't display all of them. And it doesn't show TTL either.

Your fix uses `$memcached->getAllKeys()` witch works only in Memcache**d** and also has the same problem as `cachedump`. Memcache and Memcached are different extensions and my tool must support both of them. I spent a lot of time fixing the compatibility between them and it's really not an easy task. Overall, both of these extensions are really bad.

If you are using Windows, update Memcached server to this version https://github.com/nono303/memcached , I use it with Laragon localhost server. Specifically this version https://github.com/nono303/memcached/tree/master/libevent-2.1/x64


I closing this issue because it's a problem with your server and not tool it self.
