### ISSUE TITLE
Suggest pagination load for memcache dashboard

### ISSUE THREAD

**Issue by dtduc-git** [RobiNN1/phpCacheAdmin#25]
### Proposal

Hi,

First, I would like to say thank you for your tool, it's really awesome and helpful for us. 

However, we're having a case when memcached server in production which have a lot of key (12295 key) and Memory Usage is 88,40MB. It takes 23-25 seconds to load the dashboard and about same time to perform every action in that dashboard. 

When troubleshooting, I see dashboard seems to load all key by every action that leads to this issue. And opcache or apcu not helpful for this case.

Therefore, I think if we have a feature like pagination load + "scan more" or "load more" button for listing and searching, it would be great.

I'm not an expert for PHP so pls correct me if I'm wrong :). If you have better idea for configuration to speedup the loading time, I'm looking forward to hearing about that.

About our version:
- PHP version: 8.2.9
- PHP-Memcache version: 8.2 (have a problem with php-memcached to connect gcp memcache, so we had to switch to php-memcache)
- PHP OPCache extension v8.2.9
- PHP APCu extension v5.1.22

### Motivation and context

If this change can be implemented, It would be helpful to manage large memcache server.

**Comment by RobiNN1** [comment]
Hi, you forgot to mention an important info, phpCacheAdmin version (it's at the bottom of the sidebar).
There was a problem with that and it was fixed in v1.5.3. Before this version, the load time with 10k keys was more than one minute. It should be under 10s now.

**Comment by dtduc-git** [comment]
Hi @RobiNN1 , thanks for your quick response. 

The phpCacheAdmin version we're using is: v1.6.0 - the latest version. 

<img width="204" alt="Screenshot 2023-09-07 at 4 26 37 PM" src="https://github.com/RobiNN1/phpCacheAdmin/assets/40049950/92c96cc6-c1da-488b-b29d-724c08ce04a1">

In case you would like to know, here is our Dockerfile:
```
FROM php:8.2-apache

RUN apt update

RUN apt install -y vim curl libz-dev libmemcached-dev zlib1g-dev libssl-dev

# INSTALL REDIS
RUN pecl install redis && docker-php-ext-enable redis

# INSTALL MEMCACHE
RUN pecl install memcache && docker-php-ext-enable memcache

# # INSTALL MEMCACHED
# RUN pecl install memcached && docker-php-ext-enable memcached

RUN docker-php-ext-enable opcache

RUN pecl install apcu && docker-php-ext-enable apcu

RUN rm -rf /tmp/pear

WORKDIR /var/www/html
RUN chmod 777 /var/www/html
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

COPY . /var/www/html

CMD apache2-foreground
```

Thanks in advance if there's a way to speedup the loading performance.

**Comment by RobiNN1** [comment]
I can try to optimize more, but I'm not sure if that's even possible because Memcached does not have a native pagination mechanism like Redis. Under the hood it loads all the keys (with `lru_crawler metadump all` command) and my tool then creates the pagination from that. Also it's take time to process such a large amount of data.


Output from `lru_crawler metadump all` (via telnet)
![image](https://github.com/RobiNN1/phpCacheAdmin/assets/11664877/5bd286ed-dba2-4680-a0dd-0c65b97261b5)
Memcached server returns all keys at once and then my tool need to process every single line.

**Comment by RobiNN1** [comment]
This was one of my ideas, but it's not good because what if you add new key? Or any key is expired. Expiration is updated on every reload. Maybe store this for few seconds 🤷‍♂️.

It doesn't matter which extension you use, I can actually drop support for those extensions because none of them has support for `lru_crawler` or the proper solution to get all the keys. phpCacheAdmin uses my own php client for this.

**Comment by dtduc-git** [comment]
Thanks for your response. I will review your codebase and see if I'm missing something.  I'm curious about your point - `Before this version, the load time with 10k keys was more than one minute. It should be under 10s now.`

**Comment by RobiNN1** [comment]
These classes are responsible for this

https://github.com/RobiNN1/phpCacheAdmin/blob/master/src/Dashboards/Memcached/Compatibility/CommandTrait.php
https://github.com/RobiNN1/phpCacheAdmin/blob/master/src/Dashboards/Memcached/Compatibility/MemcachedKeys.php

Well, according to my tests with 10k, before it took over 1 minute. And after fixes I managed to get 7s.
